name: Move PDFs to PDFS Folder

on:
  workflow_dispatch:

jobs:
  move-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set Git user
        run: |
          git config --global user.name "Derech Olam Ministries Int'l"
          git config --global user.email "lastwarners2024@gmail.com"

      - name: Run move-pdfs.js from ROOT
        run: node move-pdfs.js

      - name: Push commit to GitHub
        run: git push origin HEAD
